USE [VBSPINFOR]
GO

/****** Object:  StoredProcedure [dbo].[usp_KH_CBTD]    Script Date: 17/02/2017 10:49:08 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




--region [dbo].[usp_UpdateDIENBAO]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Administrator using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_UpdateDIENBAO]
-- Date Generated: Saturday, July 11, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_KH_CBTD]
@MaPos varchar(6),
@TuNgay date,
@DenNgay date,
@Mau varchar(1)
as
Begin
	--Ngay la ngay so lieu ky truoc, dengay la ngay so lieu ky nay
	--@Mau =1 CBTD, 2,CBKT, 3 XA
	declare @MaCn varchar(6)='003005',@cot nvarchar(100),@SoThang int=dbo.SoThang(@TuNgay,@DenNgay),@Dv int =1000	
	,@EndDayOfYearPre date=DATEADD(dd,-1,DATEADD(yy, DATEDIFF(yy,0,@DenNgay),0))
	,@EndDayOfYear date=DATEADD(yy, DATEDIFF(yy,0,@DenNgay) + 1, -1)	
	,@FirstDayOfYear date=DATEADD(yy, DATEDIFF(yy,0,@DenNgay), 0)		
	,@EndDayOfMonth date=DATEADD(d, -1, DATEADD(m, DATEDIFF(m, 0,DATEADD(yy, DATEDIFF(yy,0,@DenNgay), 0)) + 1, 0))	
	,@EndDayOfMonthPre date=DATEADD(d, -1, DATEADD(m, DATEDIFF(m, 0, @DenNgay), 0))
	,@EndDayOfMonthNow date=DATEADD(d, -1, DATEADD(m, DATEDIFF(m, 0, @DenNgay) + 1, 0))
	,@StarOfWeek date=DATEADD(DAY, 2 - DATEPART(WEEKDAY, @DenNgay), CAST(@DenNgay AS DATE))
	,@EndOfWeek date=DATEADD(DAY, 6 - DATEPART(WEEKDAY, @DenNgay), CAST(@DenNgay AS DATE));	
	if @SoThang=0 set @SoThang=1
	if @EndDayOfMonthNow=@DenNgay or @EndOfWeek=@DenNgay
		Begin
		
			if @MaPos='003000'
				Begin
					select a.KU_NGAYBC NGAY,a.KU_MAPGD,LEFT(a.KU_MADP,6) MAXA,a.KU_MAKH,a.KU_DNOTHAN,a.KU_DNOQHAN
					,a.KU_DNOKHOANH,a.KU_DNOTHAN+a.KU_DNOQHAN+a.KU_DNOKHOANH DUNO,a.KU_LSUAT,LEFT(a.KU_NGAY_TLAI,10) NG_TRLAI
					,(case when a.KU_NGAY_TLAI <= @TuNgay then ((a.KU_DNOTHAN+a.KU_DNOQHAN)*a.KU_LSUAT/1200.00) else 0 end) LAITHANG
					into #hsku_tr from HSKU a where a.KU_NGAYBC=@TuNgay 
					
					select a.KU_NGAYBC NGAY,a.KU_HTHUCVAY,a.KU_TTMONVAY,a.KU_MATO,
					a.KU_MAPGD,LEFT(a.KU_MADP,6) MAXA,a.KU_MAKH,a.KU_DNOTHAN,a.KU_DNOQHAN,a.KU_DNOKHOANH,a.KU_DNOTHAN+a.KU_DNOQHAN+a.KU_DNOKHOANH DUNO,a.KU_LAI_TT
					into #hsku from HSKU a where a.KU_NGAYBC=@DenNgay 
					select LEFT(a.CS_MADP,6) MAXA,a.* into #c3 from CASA a where a.CS_NGAYBC=@DenNgay and a.CS_SP_TK='105'

					select a.KU_MAPGD,SUM(KU_DNOQHAN) DNQH_TR,SUM(DUNO) DUNO_TR,SUM(LAITHANG) LAITHANG into #sl_tr from #hsku_tr a group by a.KU_MAPGD
					select a.KU_MAPGD,SUM(KU_DNOQHAN) DNQH,SUM(DUNO) DUNO,SUM(KU_LAI_TT) LAI_TT
					,0 Z_KH				
					into #sl from #hsku a group by a.KU_MAPGD
					--=================================================================================
					select a.KU_MAPGD,a.MAXA,count (distinct a.KU_MAKH) SHKU,count(distinct b.CS_MAKH) SHCS
					into #sh1 from 
					(
						select a.* from #hsku a 
						where a.KU_TTMONVAY<>'CLOSE' and a.KU_DNOTHAN+a.KU_DNOQHAN+a.KU_DNOKHOANH>0
						and a.KU_MATO is not null
					) a 
					left join
						(select a.* from #c3 a where a.CS_TTSO_TK='A' and a.CS_SP_TK='105' and a.CS_MATO is not null
						 and a.CS_MAKH not in (select a.KU_MAKH from #hsku a 
						where a.KU_TTMONVAY<>'CLOSE' and a.KU_DNOTHAN+a.KU_DNOQHAN+a.KU_DNOKHOANH>0
						and a.KU_MATO is not null)) b
					on a.MAXA=b.MAXA
					group by a.KU_MAPGD,a.MAXA
					
					--xu ly lai phan tong so khach hang
					update a set a.Z_KH=b.SHKU+b.SHCS from #sl a
					,(select a.KU_MAPGD,SUM(a.SHKU) SHKU,SUM(a.SHCS) SHCS from #sh1 a group by a.KU_MAPGD) b where a.KU_MAPGD=b.KU_MAPGD
					--=================================================================						
					select a.CS_MAPGD,sum(a.CS_SODU_TK) DUTK into #cs_tr from CASA a 
					where a.CS_NGAYBC=@TuNgay and a.CS_SP_TK='105' and a.CS_TTSO_TK='A' and a.CS_SODU_TK>0 and a.CS_MATO is not null group by a.CS_MAPGD			
					select a.CS_MAPGD
					,COUNT(distinct (case when a.CS_M_GUITK>0 then a.CS_MAKH else '' end)) Z_GUI
					,COUNT(distinct (case when a.CS_SODU_TK>0 then a.CS_MAKH else '' end)) Z_TK
					,sum(a.CS_SODU_TK) DUTK into #cs from CASA a where a.CS_NGAYBC=@DenNgay and a.CS_SP_TK='105' and a.CS_TTSO_TK='A' and a.CS_SODU_TK>0 and a.CS_MATO is not null group by a.CS_MAPGD
					select '0' as Mau,@TuNgay as TuNgay,@DenNgay as DenNgay,'' as MACB,'' as TENCB,N'Tổng Hợp' as PO_TEN,N'Đồng Hới - Quảng Bình' as PO_DIACHI,'' as TENXA,'' TENTINH,ROW_NUMBER() over (order by (select 1)) as cot1
					,d.TEN as cot2,b.DUNO_TR cot31,b.DNQH_TR cot41,a.DUNO/@Dv as cot3,a.DNQH/@Dv as cot4,a.DNQH*100/a.DUNO as cot5,(a.DNQH*100/a.DUNO)-(b.DNQH_TR*100/b.DUNO_TR) as cot6
					,a.LAI_TT/@Dv as cot7,b.LAITHANG/@Dv as cot8
					,a.LAI_TT*100/b.LAITHANG as cot9,c.Z_GUI as cot10,a.Z_KH as cot11,c.Z_GUI*100/a.Z_KH as cot12
					,c.Z_TK as cot13,c.DUTK/@Dv as cot14,(c.DUTK-e.DUTK)/@Dv as cot15
					from #sl a,#sl_tr b,#cs c,DMHUYEN d,#cs_tr e
					where a.KU_MAPGD=b.KU_MAPGD and a.KU_MAPGD=c.CS_MAPGD and right(a.KU_MAPGD,4)=d.MA and a.KU_MAPGD=e.CS_MAPGD
					order by a.KU_MAPGD
				End
			else
				Begin
						select a.KU_NGAYBC NGAY,a.KU_MAPGD,LEFT(a.KU_MADP,6) MAXA,a.KU_MATO,a.KU_MAKH,a.KU_DNOTHAN
						,a.KU_DNOQHAN,a.KU_DNOKHOANH,a.KU_DNOTHAN+a.KU_DNOQHAN+a.KU_DNOKHOANH DUNO
						,a.KU_LSUAT,LEFT(a.KU_NGAY_TLAI,10) NG_TRLAI
						,(case when a.KU_NGAY_TLAI <= @TuNgay then ((a.KU_DNOTHAN+a.KU_DNOQHAN)*a.KU_LSUAT/1200.00) else 0 end) LAITHANG
						into #hsku_tr1 from HSKU a where a.KU_NGAYBC=@TuNgay and a.KU_MAPGD=@MaPos 
						
						select a.KU_NGAYBC NGAY,A.KU_TTMONVAY,a.KU_MAPGD,LEFT(a.KU_MADP,6) MAXA,a.KU_MATO
						,a.KU_HTHUCVAY,a.KU_MAKH,a.KU_DNOTHAN,a.KU_DNOQHAN,a.KU_DNOKHOANH,a.KU_DNOTHAN+a.KU_DNOQHAN+a.KU_DNOKHOANH DUNO,a.KU_LAI_TT
						into #hsku1 from HSKU a where a.KU_NGAYBC=@DenNgay and a.KU_MAPGD=@MaPos 
						
						select LEFT(a.CS_MADP,6) MAXA,a.* into #c1 from CASA a where a.CS_NGAYBC=@DenNgay and a.CS_MAPGD=@MaPos and a.CS_SP_TK='105'
						
						select a.KU_MAPGD,a.MAXA,SUM(KU_DNOQHAN) DNQH_TR,SUM(DUNO) DUNO_TR,SUM(LAITHANG) LAITHANG into #sl_tr1 
						from #hsku_tr1 a group by a.KU_MAPGD,a.MAXA
						--====================03/11/2016==================================
						select a.MAXA,count (distinct a.KU_MAKH) SHKU,count(distinct b.CS_MAKH) SHCS
						into #sh from 
						(
							select a.* from #hsku1 a 
							where a.KU_TTMONVAY<>'CLOSE' and a.KU_DNOTHAN+a.KU_DNOQHAN+a.KU_DNOKHOANH>0
							and a.KU_MATO is not null
						) a 
						left join
							(select a.* from #c1 a where a.CS_TTSO_TK='A' and a.CS_SP_TK='105' and a.CS_MATO is not null
							 and a.CS_MAKH not in (select a.KU_MAKH from #hsku1 a 
							where a.KU_TTMONVAY<>'CLOSE' and a.KU_DNOTHAN+a.KU_DNOQHAN+a.KU_DNOKHOANH>0
							and a.KU_MATO is not null)) b
						on a.MAXA=b.MAXA
						group by a.MAXA
						---------------------------------------------------------
						select a.KU_MAPGD,a.MAXA,SUM(KU_DNOQHAN) DNQH,SUM(DUNO) DUNO,SUM(KU_LAI_TT) LAI_TT
						,0 Z_KH				
						into #sl1 from #hsku1 a group by a.KU_MAPGD,a.MAXA
						--xu ly lai phan tong so khach hang
						update a set a.Z_KH=b.SHKU+b.SHCS from #sl1 a,#sh b	where a.MAXA=b.MAXA
						--=================================================================						
						select a.CS_MAPGD,LEFT(a.CS_MADP,6) MAXA,sum(a.CS_SODU_TK) DUTK into #cs_tr1 from CASA a 
						where a.CS_NGAYBC=@TuNgay and a.CS_MAPGD=@MaPos and a.CS_SP_TK='105' and a.CS_TTSO_TK='A' and a.CS_SODU_TK>0 and a.CS_MATO is not null group by a.CS_MAPGD,LEFT(a.CS_MADP,6)			
						select a.CS_MAPGD,LEFT(a.CS_MADP,6) MAXA,COUNT(distinct (case when a.CS_M_GUITK>0 then a.CS_MAKH else '' end)) Z_GUI
						,COUNT(distinct (case when a.CS_SODU_TK>0 then a.CS_MAKH else '' end)) Z_TK
						,sum(a.CS_SODU_TK) DUTK into #cs1 from #c1 a where a.CS_NGAYBC=@DenNgay and a.CS_MAPGD=@MaPos and a.CS_SP_TK='105' and a.CS_TTSO_TK='A' and a.CS_SODU_TK>0 and a.CS_MATO is not null group by a.CS_MAPGD,LEFT(a.CS_MADP,6)						
						
						
					if @Mau='1'
						begin
							select @Mau as Mau,@TuNgay as TuNgay,@DenNgay as DenNgay,h.CMT_CBTD as MACB,h.TEN_CBTD as TENCB,f.PO_TEN,f.PO_DIACHI,g.TEN as TENXA,'' TENTINH,ROW_NUMBER() over (order by (select 1)) as cot1
							,g.TEN as cot2,b.DUNO_TR cot31,b.DNQH_TR cot41,a.DUNO/@Dv as cot3,a.DNQH/@Dv as cot4,a.DNQH*100/a.DUNO as cot5,(a.DNQH*100/a.DUNO)-(b.DNQH_TR*100/b.DUNO_TR) as cot6
							,a.LAI_TT/@Dv as cot7,b.LAITHANG/@Dv as cot8
							,a.LAI_TT*100/b.LAITHANG as cot9,c.Z_GUI as cot10,a.Z_KH as cot11,c.Z_GUI*100/a.Z_KH as cot12
							,c.Z_TK as cot13,c.DUTK/@Dv as cot14,(c.DUTK-e.DUTK)/@Dv as cot15
							from #sl1 a,#sl_tr1 b,#cs1 c,DMHUYEN d,#cs_tr1 e,DMPOS f,DMXA g,CBTD h
							where a.KU_MAPGD=b.KU_MAPGD and a.KU_MAPGD=c.CS_MAPGD and right(a.KU_MAPGD,4)=d.MA and a.KU_MAPGD=e.CS_MAPGD and a.KU_MAPGD=f.PO_MA and a.MAXA=b.MAXA and a.MAXA=c.MAXA and a.MAXA=e.MAXA and a.MAXA=g.MA and g.CMT_CBTD=h.CMT_CBTD
							order by a.MAXA								
						end
					else if @Mau='2'
						begin
							select @Mau as Mau,@TuNgay as TuNgay,@DenNgay as DenNgay,h.KT_CMT as MACB,h.KT_TEN as TENCB,f.PO_TEN,f.PO_DIACHI,g.TEN as TENXA,'' TENTINH,ROW_NUMBER() over (order by (select 1)) as cot1
							,g.TEN as cot2,b.DUNO_TR cot31,b.DNQH_TR cot41,a.DUNO/@Dv as cot3,a.DNQH/@Dv as cot4,a.DNQH*100/a.DUNO as cot5,(a.DNQH*100/a.DUNO)-(b.DNQH_TR*100/b.DUNO_TR) as cot6
							,a.LAI_TT/@Dv as cot7,b.LAITHANG/@Dv as cot8
							,a.LAI_TT*100/b.LAITHANG as cot9,c.Z_GUI as cot10,a.Z_KH as cot11,c.Z_GUI*100/a.Z_KH as cot12
							,c.Z_TK as cot13,c.DUTK/@Dv as cot14,(c.DUTK-e.DUTK)/@Dv as cot15
							from #sl1 a,#sl_tr1 b,#cs1 c,DMHUYEN d,#cs_tr1 e,DMPOS f,DMXA g,CBKT h
							where a.KU_MAPGD=b.KU_MAPGD and a.KU_MAPGD=c.CS_MAPGD and right(a.KU_MAPGD,4)=d.MA and a.KU_MAPGD=e.CS_MAPGD and a.KU_MAPGD=f.PO_MA and a.MAXA=b.MAXA and a.MAXA=c.MAXA and a.MAXA=e.MAXA and a.MAXA=g.MA and g.CMT_CBKT=h.KT_CMT
							order by a.MAXA								
						end
					else
						begin				
							select '0' as Mau,@TuNgay as TuNgay,@DenNgay as DenNgay,'' as MACB,'' as TENCB,f.PO_TEN,f.PO_DIACHI,g.TEN as TENXA,'' TENTINH,ROW_NUMBER() over (order by (select 1)) as cot1
							,g.TEN as cot2,b.DUNO_TR cot31,b.DNQH_TR cot41,a.DUNO/@Dv as cot3,a.DNQH/@Dv as cot4,a.DNQH*100/a.DUNO as cot5,(a.DNQH*100/a.DUNO)-(b.DNQH_TR*100/b.DUNO_TR) as cot6
							,a.LAI_TT/@Dv as cot7,b.LAITHANG/@Dv as cot8
							,a.LAI_TT*100/b.LAITHANG as cot9,c.Z_GUI as cot10,a.Z_KH as cot11,c.Z_GUI*100/a.Z_KH as cot12
							,c.Z_TK as cot13,c.DUTK/@Dv as cot14,(c.DUTK-e.DUTK)/@Dv as cot15
							from #sl1 a,#sl_tr1 b,#cs1 c,DMHUYEN d,#cs_tr1 e,DMPOS f,DMXA g
							where a.KU_MAPGD=b.KU_MAPGD and a.KU_MAPGD=c.CS_MAPGD and right(a.KU_MAPGD,4)=d.MA and a.KU_MAPGD=e.CS_MAPGD and a.KU_MAPGD=f.PO_MA and a.MAXA=b.MAXA and a.MAXA=c.MAXA and a.MAXA=e.MAXA and a.MAXA=g.MA
							order by a.MAXA	
						end
					
						
				End	
				
		End	
	else	
	Begin --==========================================Daily===========================================
		
		
			if @MaPos='003000'
				Begin
					select a.KU_NGAYBC NGAY,a.KU_MAPGD,LEFT(a.KU_MADP,6) MAXA,a.KU_MAKH,a.KU_DNOTHAN,a.KU_DNOQHAN
					,a.KU_DNOKHOANH,a.KU_DNOTHAN+a.KU_DNOQHAN+a.KU_DNOKHOANH DUNO,a.KU_LSUAT,LEFT(a.KU_NGAY_TLAI,10) NG_TRLAI
					,(case when a.KU_NGAY_TLAI <= @TuNgay then ((a.KU_DNOTHAN+a.KU_DNOQHAN)*a.KU_LSUAT/1200.00) else 0 end) LAITHANG
					into #hsku_tra from HSKU a where a.KU_NGAYBC=@TuNgay 
					
					select a.KU_NGAYBC NGAY,a.KU_HTHUCVAY,a.KU_TTMONVAY,a.KU_MATO,
					a.KU_MAPGD,LEFT(a.KU_MADP,6) MAXA,a.KU_MAKH,a.KU_DNOTHAN,a.KU_DNOQHAN,a.KU_DNOKHOANH,a.KU_DNOTHAN+a.KU_DNOQHAN+a.KU_DNOKHOANH DUNO,a.KU_M_LAI_TT KU_LAI_TT
					into #cv from HSCV_DAILY a where a.KU_NGAYBC=@DenNgay 
					select LEFT(a.CS_MADP,6) MAXA,a.* into #c4 from CASA_DAILY a where a.CS_NGAYBC=@DenNgay and a.CS_SP_TK='105'
					
					select a.KU_MAPGD,SUM(KU_DNOQHAN) DNQH_TR,SUM(DUNO) DUNO_TR,SUM(LAITHANG) LAITHANG into #sl_tra from #hsku_tra a group by a.KU_MAPGD
					select a.KU_MAPGD,SUM(KU_DNOQHAN) DNQH,SUM(DUNO) DUNO,SUM(KU_LAI_TT) LAI_TT
					,0 Z_KH				
					into #sla from #cv a group by a.KU_MAPGD
					--===============================================04/11/2016==============================
					select a.KU_MAPGD,a.MAXA,count (distinct a.KU_MAKH) SHKU,count(distinct b.CS_MAKH) SHCS
					into #sh2 from 
					(
						select a.* from #cv a 
						where a.KU_TTMONVAY<>'CLOSE' and a.KU_DNOTHAN+a.KU_DNOQHAN+a.KU_DNOKHOANH>0
						and a.KU_MATO is not null
					) a 
					left join
						(select a.* from #c4 a where a.CS_TTSO_TK='A' and a.CS_SP_TK='105' and a.CS_MATO is not null
						 and a.CS_MAKH not in (select a.KU_MAKH from #cv a 
						where a.KU_TTMONVAY<>'CLOSE' and a.KU_DNOTHAN+a.KU_DNOQHAN+a.KU_DNOKHOANH>0
						and a.KU_MATO is not null)) b
					on a.MAXA=b.MAXA
					group by a.KU_MAPGD,a.MAXA
					
					--xu ly lai phan tong so khach hang
					update a set a.Z_KH=b.SHKU+b.SHCS from #sla a
					,(select a.KU_MAPGD,SUM(a.SHKU) SHKU,SUM(a.SHCS) SHCS from #sh2 a group by a.KU_MAPGD) b where a.KU_MAPGD=b.KU_MAPGD
					--=================================================================						
					
					select a.CS_MAPGD,sum(a.CS_SODU_TK) DUTK into #cs_tra from CASA a 
					where a.CS_NGAYBC=@TuNgay and a.CS_SP_TK='105' and a.CS_TTSO_TK='A' and a.CS_SODU_TK>0 and a.CS_MATO is not null group by a.CS_MAPGD			
					select a.CS_MAPGD
					,COUNT(distinct (case when a.CS_M_GUITK>0 then a.CS_MAKH else '' end)) Z_GUI
					,COUNT(distinct (case when a.CS_SODU_TK>0 then a.CS_MAKH else '' end)) Z_TK
					,sum(a.CS_SODU_TK) DUTK into #csa from CASA_DAILY a where a.CS_NGAYBC=@DenNgay and a.CS_SP_TK='105' and a.CS_TTSO_TK='A' and a.CS_SODU_TK>0 and a.CS_MATO is not null group by a.CS_MAPGD
					select '0' as Mau,@TuNgay as TuNgay,@DenNgay as DenNgay,'' as MACB,'' as TENCB,N'Tổng Hợp' as PO_TEN,N'Đồng Hới - Quảng Bình' as PO_DIACHI,'' as TENXA,'' TENTINH,ROW_NUMBER() over (order by (select 1)) as cot1
					,d.TEN as cot2,b.DUNO_TR cot31,b.DNQH_TR cot41,a.DUNO/@Dv as cot3,a.DNQH/@Dv as cot4,a.DNQH*100/a.DUNO as cot5,(a.DNQH*100/a.DUNO)-(b.DNQH_TR*100/b.DUNO_TR) as cot6
					,a.LAI_TT/@Dv as cot7,b.LAITHANG/@Dv as cot8
					,a.LAI_TT*100/b.LAITHANG as cot9,c.Z_GUI as cot10,a.Z_KH as cot11,c.Z_GUI*100/a.Z_KH as cot12
					,c.Z_TK as cot13,c.DUTK/@Dv as cot14,(c.DUTK-e.DUTK)/@Dv as cot15
					from #sla a,#sl_tra b,#csa c,DMHUYEN d,#cs_tra e
					where a.KU_MAPGD=b.KU_MAPGD and a.KU_MAPGD=c.CS_MAPGD and right(a.KU_MAPGD,4)=d.MA and a.KU_MAPGD=e.CS_MAPGD
					order by a.KU_MAPGD
				End
			else --========================================Daily POS===============================================
				Begin
						select a.KU_NGAYBC NGAY,a.KU_MAPGD,LEFT(a.KU_MADP,6) MAXA,a.KU_MATO,a.KU_MAKH,a.KU_DNOTHAN
						,a.KU_DNOQHAN,a.KU_DNOKHOANH,a.KU_DNOTHAN+a.KU_DNOQHAN+a.KU_DNOKHOANH DUNO
						,a.KU_LSUAT,LEFT(a.KU_NGAY_TLAI,10) NG_TRLAI
						,(case when a.KU_NGAY_TLAI <= @TuNgay then ((a.KU_DNOTHAN+a.KU_DNOQHAN)*a.KU_LSUAT/1200.00) else 0 end) LAITHANG
						into #hsku_tr1a from HSKU a where a.KU_NGAYBC=@TuNgay and a.KU_MAPGD=@MaPos 
						
						select a.KU_NGAYBC NGAY,A.KU_TTMONVAY,a.KU_MAPGD,LEFT(a.KU_MADP,6) MAXA,a.KU_MATO
						,a.KU_HTHUCVAY,a.KU_MAKH,a.KU_DNOTHAN,a.KU_DNOQHAN,a.KU_DNOKHOANH,a.KU_DNOTHAN+a.KU_DNOQHAN+a.KU_DNOKHOANH DUNO,a.KU_M_LAI_TT KU_LAI_TT
						into #hsku1a from HSCV_DAILY a where a.KU_NGAYBC=@DenNgay and a.KU_MAPGD=@MaPos 
						
						select LEFT(a.CS_MADP,6) MAXA,a.* into #c2 from CASA_DAILY a where a.CS_NGAYBC=@DenNgay and a.CS_MAPGD=@MaPos and a.CS_SP_TK='105'
						
						select a.KU_MAPGD,a.MAXA,SUM(KU_DNOQHAN) DNQH_TR,SUM(DUNO) DUNO_TR,SUM(LAITHANG) LAITHANG into #sl_tr1a 
						from #hsku_tr1a a group by a.KU_MAPGD,a.MAXA
						select a.KU_MAPGD,a.MAXA,SUM(KU_DNOQHAN) DNQH,SUM(DUNO) DUNO,SUM(KU_LAI_TT) LAI_TT
						,0 Z_KH				
						into #sl1a from #hsku1a a group by a.KU_MAPGD,a.MAXA
						--====================================04/11/2016================================
						--xu ly lai phan tong so khach hang
						select a.MAXA,count (distinct a.KU_MAKH) SHKU,count(distinct b.CS_MAKH) SHCS
						into #sh3 from 
						(
							select a.* from #hsku1a a 
							where a.KU_TTMONVAY<>'CLOSE' and a.KU_DNOTHAN+a.KU_DNOQHAN+a.KU_DNOKHOANH>0
							and a.KU_MATO is not null
						) a 
						left join
							(select a.* from #c2 a where a.CS_TTSO_TK='A' and a.CS_SP_TK='105' and a.CS_MATO is not null
							 and a.CS_MAKH not in (select a.KU_MAKH from #hsku1a a 
							where a.KU_TTMONVAY<>'CLOSE' and a.KU_DNOTHAN+a.KU_DNOQHAN+a.KU_DNOKHOANH>0
							and a.KU_MATO is not null)) b
						on a.MAXA=b.MAXA
						group by a.MAXA
						update a set a.Z_KH=b.SHKU+b.SHCS from #sl1a a,#sh3 b	where a.MAXA=b.MAXA
						--=================================================================						
						
						select a.CS_MAPGD,LEFT(a.CS_MADP,6) MAXA,sum(a.CS_SODU_TK) DUTK into #cs_tr1a from CASA a 
						where a.CS_NGAYBC=@TuNgay and a.CS_MAPGD=@MaPos and a.CS_SP_TK='105' and a.CS_TTSO_TK='A' and a.CS_SODU_TK>0 and a.CS_MATO is not null group by a.CS_MAPGD,LEFT(a.CS_MADP,6)			
						select a.CS_MAPGD,LEFT(a.CS_MADP,6) MAXA,COUNT(distinct (case when a.CS_M_GUITK>0 then a.CS_MAKH else '' end)) Z_GUI
						,COUNT(distinct (case when a.CS_SODU_TK>0 then a.CS_MAKH else '' end)) Z_TK
						,sum(a.CS_SODU_TK) DUTK into #cs1a from CASA_DAILY a where a.CS_NGAYBC=@DenNgay and a.CS_MAPGD=@MaPos and a.CS_SP_TK='105' and a.CS_TTSO_TK='A' and a.CS_SODU_TK>0 and a.CS_MATO is not null group by a.CS_MAPGD,LEFT(a.CS_MADP,6)
					if @Mau='1'
						begin
							select @Mau as Mau,@TuNgay as TuNgay,@DenNgay as DenNgay,h.CMT_CBTD as MACB,h.TEN_CBTD as TENCB,f.PO_TEN,f.PO_DIACHI,g.TEN as TENXA,'' TENTINH,ROW_NUMBER() over (order by (select 1)) as cot1
							,g.TEN as cot2,b.DUNO_TR cot31,b.DNQH_TR cot41,a.DUNO/@Dv as cot3,a.DNQH/@Dv as cot4,a.DNQH*100/a.DUNO as cot5,(a.DNQH*100/a.DUNO)-(b.DNQH_TR*100/b.DUNO_TR) as cot6
							,a.LAI_TT/@Dv as cot7,b.LAITHANG/@Dv as cot8
							,a.LAI_TT*100/b.LAITHANG as cot9,c.Z_GUI as cot10,a.Z_KH as cot11,c.Z_GUI*100/a.Z_KH as cot12
							,c.Z_TK as cot13,c.DUTK/@Dv as cot14,(c.DUTK-e.DUTK)/@Dv as cot15
							from #sl1a a,#sl_tr1a b,#cs1a c,DMHUYEN d,#cs_tr1a e,DMPOS f,DMXA g,CBTD h
							where a.KU_MAPGD=b.KU_MAPGD and a.KU_MAPGD=c.CS_MAPGD and right(a.KU_MAPGD,4)=d.MA and a.KU_MAPGD=e.CS_MAPGD and a.KU_MAPGD=f.PO_MA and a.MAXA=b.MAXA and a.MAXA=c.MAXA and a.MAXA=e.MAXA and a.MAXA=g.MA and g.CMT_CBTD=h.CMT_CBTD
							order by a.MAXA								
						end
					else if @Mau='2'
						begin
							select @Mau as Mau,@TuNgay as TuNgay,@DenNgay as DenNgay,h.KT_CMT as MACB,h.KT_TEN as TENCB,f.PO_TEN,f.PO_DIACHI,g.TEN as TENXA,'' TENTINH,ROW_NUMBER() over (order by (select 1)) as cot1
							,g.TEN as cot2,b.DUNO_TR cot31,b.DNQH_TR cot41,a.DUNO/@Dv as cot3,a.DNQH/@Dv as cot4,a.DNQH*100/a.DUNO as cot5,(a.DNQH*100/a.DUNO)-(b.DNQH_TR*100/b.DUNO_TR) as cot6
							,a.LAI_TT/@Dv as cot7,b.LAITHANG/@Dv as cot8
							,a.LAI_TT*100/b.LAITHANG as cot9,c.Z_GUI as cot10,a.Z_KH as cot11,c.Z_GUI*100/a.Z_KH as cot12
							,c.Z_TK as cot13,c.DUTK/@Dv as cot14,(c.DUTK-e.DUTK)/@Dv as cot15
							from #sl1a a,#sl_tr1a b,#cs1a c,DMHUYEN d,#cs_tr1a e,DMPOS f,DMXA g,CBKT h
							where a.KU_MAPGD=b.KU_MAPGD and a.KU_MAPGD=c.CS_MAPGD and right(a.KU_MAPGD,4)=d.MA and a.KU_MAPGD=e.CS_MAPGD and a.KU_MAPGD=f.PO_MA and a.MAXA=b.MAXA and a.MAXA=c.MAXA and a.MAXA=e.MAXA and a.MAXA=g.MA and g.CMT_CBKT=h.KT_CMT
							order by a.MAXA								
						end
					else
						begin				
							select '0' as Mau,@TuNgay as TuNgay,@DenNgay as DenNgay,'' as MACB,'' as TENCB,f.PO_TEN,f.PO_DIACHI,g.TEN as TENXA,'' TENTINH,ROW_NUMBER() over (order by (select 1)) as cot1
							,g.TEN as cot2,b.DUNO_TR cot31,b.DNQH_TR cot41,a.DUNO/@Dv as cot3,a.DNQH/@Dv as cot4,a.DNQH*100/a.DUNO as cot5,(a.DNQH*100/a.DUNO)-(b.DNQH_TR*100/b.DUNO_TR) as cot6
							,a.LAI_TT/@Dv as cot7,b.LAITHANG/@Dv as cot8
							,a.LAI_TT*100/b.LAITHANG as cot9,c.Z_GUI as cot10,a.Z_KH as cot11,c.Z_GUI*100/a.Z_KH as cot12
							,c.Z_TK as cot13,c.DUTK/@Dv as cot14,(c.DUTK-e.DUTK)/@Dv as cot15
							from #sl1a a,#sl_tr1a b,#cs1a c,DMHUYEN d,#cs_tr1a e,DMPOS f,DMXA g
							where a.KU_MAPGD=b.KU_MAPGD and a.KU_MAPGD=c.CS_MAPGD and right(a.KU_MAPGD,4)=d.MA and a.KU_MAPGD=e.CS_MAPGD and a.KU_MAPGD=f.PO_MA and a.MAXA=b.MAXA and a.MAXA=c.MAXA and a.MAXA=e.MAXA and a.MAXA=g.MA
							order by a.MAXA	
						end
				End	
				
		End	
End
--endregion




GO

